artifact_location: /content/drive/MyDrive/visitusmlops/YOUR_NGROK_URL_HERE/684566675055564416
creation_time: 1781975502836
experiment_id: '684566675055564416'
last_update_time: 1781975502836
lifecycle_stage: active
name: visitus_training_experiment
